export const wordBank = {
  emotions: [
    'JOY', 'SADNESS', 'ANGER', 'FEAR', 'SURPRISE', 'LOVE', 'PEACE', 'CALM', 'ANXIETY', 'HOPE', 'TRUST', 'GRATITUDE', 'COMPASSION', 'COURAGE', 'PRIDE', 'ENVY', 'JEALOUSY', 'SHAME', 'GUILT', 'CONTENT', 'BLISS', 'SERENITY', 'OPTIMISM', 'PESSIMISM', 'EMPATHY', 'APATHY', 'CONFIDENCE', 'DOUBT', 'ECSTASY', 'GRIEF'
  ],
  nature: [
    'FOREST', 'RIVER', 'MOUNTAIN', 'OCEAN', 'DESERT', 'JUNGLE', 'FLOWER', 'TREE', 'SUN', 'MOON', 'STARS', 'RAIN', 'SNOW', 'WIND', 'CLOUD', 'LEAF', 'ROOT', 'BRANCH', 'STONE', 'BEACH', 'WAVE', 'CANYON', 'MEADOW', 'ISLAND', 'VOLCANO', 'GLACIER', 'LAKE', 'POND', 'STREAM', 'WATERFALL'
  ],
  growth: [
    'LEARN', 'CHANGE', 'EVOLVE', 'IMPROVE', 'DEVELOP', 'EXPAND', 'PROGRESS', 'TRANSFORM', 'ADAPT', 'MATURE', 'FLOURISH', 'THRIVE', 'INSIGHT', 'WISDOM', 'MINDSET', 'CHALLENGE', 'EFFORT', 'PRACTICE', 'PERSIST', 'RESILIENCE', 'JOURNEY', 'POTENTIAL', 'BREAKTHROUGH', 'UNDERSTAND', 'AWARENESS', 'REFLECTION', 'PATIENCE', 'DISCIPLINE', 'GOAL', 'SUCCESS'
  ],
  resilience: [
    'STRENGTH', 'ENDURE', 'OVERCOME', 'PERSEVERE', 'BOUNCEBACK', 'HOPE', 'COURAGE', 'GRIT', 'TOUGHNESS', 'FLEXIBLE', 'ADAPT', 'RECOVER', 'SUPPORT', 'COPE', 'BELIEF', 'DETERMINED', 'UNBREAKABLE', 'PERSISTENCE', 'FORTITUDE', 'HEART', 'SPIRIT', 'SURVIVE', 'STAND', 'RISE', 'FIGHT', 'POWER', 'INNER', 'STRONG', 'MIGHT', 'VITALITY'
  ],
  creativity: [
    'IMAGINE', 'CREATE', 'INSPIRE', 'ART', 'MUSIC', 'DANCE', 'WRITE', 'POETRY', 'DESIGN', 'INNOVATE', 'DREAM', 'VISION', 'SPARK', 'MUSE', 'EXPRESS', 'ORIGINAL', 'UNIQUE', 'BUILD', 'MAKE', 'CRAFT', 'SKILL', 'TALENT', 'FLOW', 'GENIUS', 'IDEA', 'CONCEPT', 'STYLE', 'BEAUTY', 'FORM', 'AESTHETIC'
  ],
  mindfulness: [
    'BREATHE', 'PRESENT', 'AWARE', 'MOMENT', 'FOCUS', 'OBSERVE', 'ACCEPT', 'NONJUDGMENT', 'STILLNESS', 'GROUNDED', 'CENTERED', 'ATTENTION', 'SENSES', 'BODY', 'MIND', 'FEEL', 'THOUGHT', 'LETGO', 'BEING', 'PAUSE', 'SILENCE', 'CONNECTION', 'COMPASSION', 'KINDNESS', 'PEACEFUL', 'TRANQUIL', 'UNWIND', 'MEDITATE', 'INSIGHT', 'CLARITY'
  ],
};